/*
 * Copyright (c) 2026 Alibaba Group.
 * SPDX-License-Identifier: Apache-2.0
 */

/* ===================================================================
 * capabilities.h -- compile-time platform extension capability flags
 * ===================================================================
 *
 * This header normalizes the "<EXT>_SUPPORTED" presence flags declared by
 * the platform config (config/<platform>/rvtest_config.h) into 1/0 boolean
 * macros named "<EXT>_AVAILABLE", usable both in `#if` and as a value in
 * `if (...)` (e.g. to gate a test or emit TEST_SKIP).
 *
 * Design notes (read before editing):
 *
 *  1. rvtest_config.h is AUTO-GENERATED by riscv-unified-db (udb-gen). The
 *     normalized <EXT>_AVAILABLE macros therefore live HERE, in a separate
 *     hand-maintained file, and must never be added to rvtest_config.h
 *     (they would be wiped on the next regeneration).
 *
 *  2. rvtest_config.h is force-included into every C and assembly
 *     translation unit by common/Makefile.common (-include). capabilities.h
 *     is force-included the same way, right AFTER rvtest_config.h, so the
 *     <EXT>_SUPPORTED flags are already visible here. Do NOT `#include
 *     "rvtest_config.h"` from this file: CONFIG_DIR is not on the -I search
 *     path, only reachable through the absolute -include.
 *
 *  3. <EXT>_SUPPORTED is defined with NO value (e.g. `#define F_SUPPORTED`).
 *     Consequently the Linux-kernel IS_ENABLED() token trick does not work,
 *     and `#if F_SUPPORTED` is invalid ("no expression"). The robust form is
 *     the `#ifdef` guard below that derives an explicit 1/0.
 *
 *  4. This file must stay preprocessor-only (no C types or declarations) so
 *     it remains safe to force-include into assembly as well.
 *
 *  5. Extension support is config-DECLARATION driven: a suite that gates on
 *     an extension must be launched on a simulator/HW whose config declares
 *     it. Do NOT probe at runtime (misa reads or instruction traps) -- that
 *     is fragile and has produced false negatives before.
 *
 * To add a capability, copy one block and change the extension name. Keep the
 * list curated to the extensions tests actually gate on.
 * =================================================================== */

#ifndef COMMON_CAPABILITIES_H
#define COMMON_CAPABILITIES_H

/* --- Single-letter base ISA / hardware-feature extensions -------------- */

#ifdef A_SUPPORTED
#define A_AVAILABLE 1
#else
#define A_AVAILABLE 0
#endif

#ifdef C_SUPPORTED
#define C_AVAILABLE 1
#else
#define C_AVAILABLE 0
#endif

#ifdef D_SUPPORTED
#define D_AVAILABLE 1
#else
#define D_AVAILABLE 0
#endif

#ifdef F_SUPPORTED
#define F_AVAILABLE 1
#else
#define F_AVAILABLE 0
#endif

#ifdef H_SUPPORTED
#define H_AVAILABLE 1
#else
#define H_AVAILABLE 0
#endif

#ifdef I_SUPPORTED
#define I_AVAILABLE 1
#else
#define I_AVAILABLE 0
#endif

#ifdef M_SUPPORTED
#define M_AVAILABLE 1
#else
#define M_AVAILABLE 0
#endif

#ifdef Q_SUPPORTED
#define Q_AVAILABLE 1
#else
#define Q_AVAILABLE 0
#endif

#ifdef V_SUPPORTED
#define V_AVAILABLE 1
#else
#define V_AVAILABLE 0
#endif

/* --- Sm and Ss privileged extensions --------------------------------- */
/* Previously defined in common/hyp/hyp_csr.h, now centralized here. A
 * suite that touches these CSRs must still launch the simulator with the
 * declared extension (e.g. Spike _smstateen / _smcsrind / _sscsrind). */

#ifdef SMSTATEEN_SUPPORTED
#define SMSTATEEN_AVAILABLE 1
#else
#define SMSTATEEN_AVAILABLE 0
#endif

#ifdef SSCSRIND_SUPPORTED
#define SSCSRIND_AVAILABLE 1
#else
#define SSCSRIND_AVAILABLE 0
#endif

#ifdef SMCSRIND_SUPPORTED
#define SMCSRIND_AVAILABLE 1
#else
#define SMCSRIND_AVAILABLE 0
#endif

#ifdef SMCDELEG_SUPPORTED
#define SMCDELEG_AVAILABLE 1
#else
#define SMCDELEG_AVAILABLE 0
#endif

#ifdef SSCOFPMF_SUPPORTED
#define SSCOFPMF_AVAILABLE 1
#else
#define SSCOFPMF_AVAILABLE 0
#endif


#if defined(SHLCOFIDELEG_SUPPORTED)
#define SHLCOFIDELEG_AVAILABLE 1
#else
#define SHLCOFIDELEG_AVAILABLE 0
#endif

/* Shtvala: htval must hold the faulting GPA>>2 on guest page faults
 * (tightens the H-extension baseline). Gated on the platform config's
 * SHTVALA_SUPPORTED declaration; do not probe htval at runtime. */
#ifdef SHTVALA_SUPPORTED
#define SHTVALA_AVAILABLE 1
#else
#define SHTVALA_AVAILABLE 0
#endif

/* Smmpm: M-mode pointer masking (mseccfg.PMM). Gated on the platform
 * config's SMMPM_SUPPORTED declaration; do not probe mseccfg.PMM
 * writability at runtime to infer support. */
#ifdef SMMPM_SUPPORTED
#define SMMPM_AVAILABLE 1
#else
#define SMMPM_AVAILABLE 0
#endif

/* Smnpm: M/HS-mode pointer masking (menvcfg.PMM). Gated on the platform
 * config's SMNPM_SUPPORTED declaration; do not probe menvcfg.PMM
 * writability at runtime to infer support. */
#ifdef SMNPM_SUPPORTED
#define SMNPM_AVAILABLE 1
#else
#define SMNPM_AVAILABLE 0
#endif

/* Ssnpm: S/HS- and VS/VU-mode pointer masking (senvcfg.PMM, and the
 * hypervisor-side henvcfg.PMM/hstatus.HUPMM controls). Gated on the
 * platform config's SSNPM_SUPPORTED declaration; do not probe
 * senvcfg.PMM/henvcfg.PMM writability at runtime to infer support. */
#ifdef SSNPM_SUPPORTED
#define SSNPM_AVAILABLE 1
#else
#define SSNPM_AVAILABLE 0
#endif

/* --- SMMTT / Supervisor Domain Access Protection family ------------
 * Smsd provides the `mmpt`/`msdcfg` CSRs and MFENCE.PA/MINVAL.PA;
 * Smmpt provides the Memory Protection Table modes (Smmpt34/43/52/64).
 * A suite gating on these must be launched on a simulator/HW whose
 * config declares them. No currently-shipped config declares SMMTT,
 * so SMMPT_AVAILABLE is 0 and the Smmpt suite reports SKIPPED. */

#ifdef SMSD_SUPPORTED
#define SMSD_AVAILABLE 1
#else
#define SMSD_AVAILABLE 0
#endif

#ifdef SMMPT_SUPPORTED
#define SMMPT_AVAILABLE 1
#else
#define SMMPT_AVAILABLE 0
#endif

/* I/O MPT Checker (Smmtt chapter6): a memory-mapped register interface
 * plus SDCL/MPT-check datapath in the I/O subsystem. A suite gating on
 * it also needs a platform-provided MMIO base (see smmtt.Iompt/
 * iompt_platform.h). No currently-shipped config declares IOMPT, so
 * IOMPT_AVAILABLE is 0 and the I/O MPT Checker suite reports SKIPPED. */
#ifdef IOMPT_SUPPORTED
#define IOMPT_AVAILABLE 1
#else
#define IOMPT_AVAILABLE 0
#endif

/* --- Smmtt (Supervisor Domain Access Protection) extensions -------- */
/* Smsdia (Supervisor Domain Interrupt Assignment) and its guest-file
 * access extensions Smgeien/Ssgeien. A suite that gates on these must
 * be launched on a simulator/HW whose config declares them; no current
 * simulator implements this draft extension, so the suite SKIPs until
 * a platform config adds SMSDIA_SUPPORTED. */

#ifdef SMSDIA_SUPPORTED
#define SMSDIA_AVAILABLE 1
#else
#define SMSDIA_AVAILABLE 0
#endif

#ifdef SMGEIEN_SUPPORTED
#define SMGEIEN_AVAILABLE 1
#else
#define SMGEIEN_AVAILABLE 0
#endif

#ifdef SSGEIEN_SUPPORTED
#define SSGEIEN_AVAILABLE 1
#else
#define SSGEIEN_AVAILABLE 0
#endif

/* --- Zicf* control-flow-integrity extensions ------------------------- */
/* Zicfilp (landing pad) and Zicfiss (shadow stack). A suite that gates
 * on these must be launched on a simulator/HW whose config declares them
 * (e.g. Spike _zicfilp / _zicfiss). Do NOT probe menvcfg.LPE/SSE or
 * mseccfg.MLPE writability at runtime to infer support. */

#ifdef ZICFILP_SUPPORTED
#define ZICFILP_AVAILABLE 1
#else
#define ZICFILP_AVAILABLE 0
#endif

#ifdef ZICFISS_SUPPORTED
#define ZICFISS_AVAILABLE 1
#else
#define ZICFISS_AVAILABLE 0
#endif

/* --- Za* atomic / reservation-set extensions ------------------------- */
/* Zaamo (AMO subset) and Zalrsc (LR/SC subset) are implied by the A
 * extension, so their availability also honors A_SUPPORTED, matching the
 * AMO / LR-SC probe semantics the suites already used. Zabha/Zacas/
 * Zalasr/Zama16b/Za64rs/Za128rs are gated on their own config flag.
 * Gate every case on these compile-time macros; only a suite's first
 * case may trap-probe the DUT to verify alignment with the declaration. */

#if defined(ZAAMO_SUPPORTED) || defined(A_SUPPORTED)
#define ZAAMO_AVAILABLE 1
#else
#define ZAAMO_AVAILABLE 0
#endif

#if defined(ZALRSC_SUPPORTED) || defined(A_SUPPORTED)
#define ZALRSC_AVAILABLE 1
#else
#define ZALRSC_AVAILABLE 0
#endif

#ifdef ZABHA_SUPPORTED
#define ZABHA_AVAILABLE 1
#else
#define ZABHA_AVAILABLE 0
#endif

#ifdef ZACAS_SUPPORTED
#define ZACAS_AVAILABLE 1
#else
#define ZACAS_AVAILABLE 0
#endif

#ifdef ZALASR_SUPPORTED
#define ZALASR_AVAILABLE 1
#else
#define ZALASR_AVAILABLE 0
#endif

#ifdef ZAMA16B_SUPPORTED
#define ZAMA16B_AVAILABLE 1
#else
#define ZAMA16B_AVAILABLE 0
#endif

#ifdef ZA64RS_SUPPORTED
#define ZA64RS_AVAILABLE 1
#else
#define ZA64RS_AVAILABLE 0
#endif

#ifdef ZA128RS_SUPPORTED
#define ZA128RS_AVAILABLE 1
#else
#define ZA128RS_AVAILABLE 0
#endif

#ifdef ZAWRS_SUPPORTED
#define ZAWRS_AVAILABLE 1
#else
#define ZAWRS_AVAILABLE 0
#endif

/* --- Zicond integer conditional-move extension ----------------------- */
/* czero.eqz / czero.nez. The Zicond suite and the Zkt constant-time
 * suite gate on this; a suite that executes czero must be launched on
 * a simulator/HW whose config declares Zicond. */

#ifdef ZICOND_SUPPORTED
#define ZICOND_AVAILABLE 1
#else
#define ZICOND_AVAILABLE 0
#endif

/* --- Zc* compressed-instruction subsets ------------------------------ */
/* Zca (the integer compressed subset) is implied by the C extension
 * (C = Zca + Zcf(RV32) + Zcd), so its availability also honors
 * C_SUPPORTED, mirroring how ZAAMO_AVAILABLE honors A_SUPPORTED. Zcb
 * adds the c.mul/c.not/c.zext.* byte-op compressed forms. */

#if defined(ZCA_SUPPORTED) || defined(C_SUPPORTED)
#define ZCA_AVAILABLE 1
#else
#define ZCA_AVAILABLE 0
#endif

#ifdef ZCB_SUPPORTED
#define ZCB_AVAILABLE 1
#else
#define ZCB_AVAILABLE 0
#endif

/* --- Zk* scalar-cryptography extensions ------------------------------ */
/* Zkne/Zknd (AES encrypt/decrypt), Zknh (SHA2), Zksed (SM4), Zksh
 * (SM3), Zkr (entropy-source `seed` CSR). A suite that executes these
 * instructions or reads `seed` must be launched on a simulator/HW whose
 * config declares the relevant subset. */

#ifdef ZKNE_SUPPORTED
#define ZKNE_AVAILABLE 1
#else
#define ZKNE_AVAILABLE 0
#endif

#ifdef ZKND_SUPPORTED
#define ZKND_AVAILABLE 1
#else
#define ZKND_AVAILABLE 0
#endif

#ifdef ZKNH_SUPPORTED
#define ZKNH_AVAILABLE 1
#else
#define ZKNH_AVAILABLE 0
#endif

#ifdef ZKSED_SUPPORTED
#define ZKSED_AVAILABLE 1
#else
#define ZKSED_AVAILABLE 0
#endif

#ifdef ZKSH_SUPPORTED
#define ZKSH_AVAILABLE 1
#else
#define ZKSH_AVAILABLE 0
#endif

#ifdef ZKR_SUPPORTED
#define ZKR_AVAILABLE 1
#else
#define ZKR_AVAILABLE 0
#endif

/* --- Zb* bit-manipulation extensions --------------------------------- */
/* Zbb (basic), Zbkb (crypto bit-manip: pack/zip/rotates), Zbkc
 * (carry-less multiply), Zbkx (crossbar permute). */

#ifdef ZBB_SUPPORTED
#define ZBB_AVAILABLE 1
#else
#define ZBB_AVAILABLE 0
#endif

#ifdef ZBKB_SUPPORTED
#define ZBKB_AVAILABLE 1
#else
#define ZBKB_AVAILABLE 0
#endif

#ifdef ZBKC_SUPPORTED
#define ZBKC_AVAILABLE 1
#else
#define ZBKC_AVAILABLE 0
#endif

#ifdef ZBKX_SUPPORTED
#define ZBKX_AVAILABLE 1
#else
#define ZBKX_AVAILABLE 0
#endif

/* --- Zkt data-independent execution latency contract ----------------- */
/* Zkt has no CSR/misa visibility of its own; it is a timing contract
 * over the listed instruction subsets. A suite gating on it relies
 * purely on the config declaration. */

#ifdef ZKT_SUPPORTED
#define ZKT_AVAILABLE 1
#else
#define ZKT_AVAILABLE 0
#endif

/* --- Sv* virtual-memory extensions ------------------------------------ */
/* Svade (A/D update via page-fault), Svadu (hardware A/D update),
 * Svpbmt (page-based memory types), Svinval (fine-grained invalidation:
 * SINVAL.VMA / HINVAL.VVMA/GVMA).
 * A suite gating on these must be launched on a simulator/HW whose
 * config declares them. Do NOT probe menvcfg.ADUE/PBMTE writability,
 * map an A=0 page and observe the fault, or execute HINVAL at runtime
 * to infer support. */

#ifdef SVADE_SUPPORTED
#define SVADE_AVAILABLE 1
#else
#define SVADE_AVAILABLE 0
#endif

#ifdef SVADU_SUPPORTED
#define SVADU_AVAILABLE 1
#else
#define SVADU_AVAILABLE 0
#endif

#ifdef SVPBMT_SUPPORTED
#define SVPBMT_AVAILABLE 1
#else
#define SVPBMT_AVAILABLE 0
#endif

#ifdef SVINVAL_SUPPORTED
#define SVINVAL_AVAILABLE 1
#else
#define SVINVAL_AVAILABLE 0
#endif

/* Svnapot (NAPOT translation contiguity hint, misa.N / PTE bit 63).
 * QEMU's "max" CPU implements Svnapot but does not set misa.N, so a
 * runtime misa probe gives a false negative; rely on the config
 * declaration instead. */

#ifdef SVNAPOT_SUPPORTED
#define SVNAPOT_AVAILABLE 1
#else
#define SVNAPOT_AVAILABLE 0
#endif

/* --- Zicbo* cache-block operation extensions -------------------------- */
/* Zicbom (management: CBIE/CBCFE/CBME) and Zicboz (zero: CBZE). A suite
 * gating on these must be launched on a simulator/HW whose config
 * declares them. Do NOT probe menvcfg.CBIE/CBZE writability at runtime. */

#ifdef ZICBOM_SUPPORTED
#define ZICBOM_AVAILABLE 1
#else
#define ZICBOM_AVAILABLE 0
#endif

#ifdef ZICBOZ_SUPPORTED
#define ZICBOZ_AVAILABLE 1
#else
#define ZICBOZ_AVAILABLE 0
#endif

/* --- Counter / timer extensions --------------------------------------- */
/* Smcntrpmf (mcyclecfg/minstretcfg mode-based filtering) and Zicntr
 * (base counters: cycle/time/instret). Do NOT probe mcyclecfg.MINH
 * writability or trap-read the time CSR at runtime to infer support. */

#ifdef SMCNTRPMF_SUPPORTED
#define SMCNTRPMF_AVAILABLE 1
#else
#define SMCNTRPMF_AVAILABLE 0
#endif

#ifdef ZICNTR_SUPPORTED
#define ZICNTR_AVAILABLE 1
#else
#define ZICNTR_AVAILABLE 0
#endif

/* --- Ssqosid (QoS identifier: srmcfg) --------------------------------- */
/* Not declared by every platform config (e.g. qemu-rv64-max omits it),
 * so SSQOSID_AVAILABLE is 0 there and the suite reports SKIPPED --
 * matching the previous runtime srmcfg probe behaviour. */

#ifdef SSQOSID_SUPPORTED
#define SSQOSID_AVAILABLE 1
#else
#define SSQOSID_AVAILABLE 0
#endif

/* --- Smaia (advanced interrupt architecture, M/HS side: hvien etc.) --- */
/* A suite gating on hvien/hvip virtual-interrupt controls must be
 * launched on a simulator/HW whose config declares Smaia. Do NOT
 * trap-read hvien at runtime to infer support. */

#ifdef SMAIA_SUPPORTED
#define SMAIA_AVAILABLE 1
#else
#define SMAIA_AVAILABLE 0
#endif

#endif /* COMMON_CAPABILITIES_H */
