# =====================================================================
# Sscsrind Extension Verification Test
# =====================================================================

TARGET = sscsrind_test.elf


EXT_OBJS = \
    main.o \
    tests/test_register.o

ENABLE_VM  = 1

include ../common/Makefile.common
